_checkgame almost finished

diff --git a/humblepie b/humblepie
--- a/humblepie
+++ b/humblepie
@@ -1,55 +1,73 @@
 #!/usr/bin/env bash
 
-_archive="source[0]%%:*"
-#_humblebundletorrent=""
 [[ -f PKGBUILD ]] || {
   echo "This script requires the game's PKGBUILD to function."
   echo "Please extract the tarball for the desired game and run this script again."
 }
+
 . PKGBUILD
-for group in "${groups[@]}"; do
-  _key="_humblebundle${group:19}key"
-  [[ -n "${!_key}" ]] && break
-  # if [[  ]]
-  #   continue 
-  # else 
-  #   case foo in
-  #     "$_humblebundlefrozenkey")
-  #     "$_humblebundlesynapsekey")
-  #     "$_humblevoxatronkey")
-  #   esac
-  # fi
-done
-                      #|| -n "${!_key}" 
-[[ -f "${!_archive}" ]] || {
-  _path="Absolute path (omit trailing slashes): "
-  [[ -z "${_humblebundledir}" ]] && {
-  echo "Specify the path to the directory containing ${!_archive}"
-  echo -n "${_path}"
-  while read -r _dir; do
-  [[ -f "${_dir}/${!_archive}" ]] && {
-    ln -s "${_dir}/${!_archive}" .
-    continue
-    }
-  done
-  }
+_archive="source[0]%%:*"
+hibenv=('_humblebundle1key'
+        '_humblebundle2key'
+        '_humblebundle3key'
+        '_humblebundle4key' 
+        '_humblebundleVkey')
+hibvox=('_humblevoxatronkey')
+hibfb=('_humblebundlefrozenkey')
+hibfs=('_humblebundlesynapsekey')
+hibandroid=('_humblebundleandroidkey'
+            '_humblebundleandroid2key')
 
-  echo "_humblebundle4key or _humblebundleVkey should be exported in your environment!"
-  echo "Alternatively, place the download into ${_humblebundledir} and retry."
-  echo "Y to specify path to existing download, blank to specify your humble indie bundle key."
-  read -r _cont
-
-  case "${_cont}" in
-    [yY]) 
-      ;;
-    *) echo "Specify your humble indie bundle key."
-      echo -n "Humble Indie Bundle key: "
-      read -r _hib
-      [[ -n "${_hib}" ]] && _key="_hib"
-      ;;
-  esac
+[[ -f "${_humblebundledir}/${!_archive}" ]] && {
+  ln -sf "${_humblebundledir}/${!_archive}" .
 }
-  [[ -f "${!_archive}" || -z "${!_key}" ]] || {
+
+_genkeyarray() {
+
+_checkkey
+}
+
+_checkkey() {
+  for keyvar in "${_keyarray[@]}"; do
+  _key="keyvar"
+  [[ -n "${!_key}" ]] && break
+  done
+  _checkgame
+}
+
+_checkgame() {
+  [[ -f "${!_archive}" ]] || {
+    local _prompt="Absolute path (omit trailing slashes): "
+    [[ -d "${_humblebundledir}" ]] && {
+    echo "Specify the path to the directory containing ${!_archive}"
+    echo -n "${_prompt}"
+    while read -er _dir; do
+      while [[ -f "${_dir}/${!_archive}" ]]; do
+        [[ $(md5sum "${_dir}/${!_archive}") == ${md5sum[0]} ]] {
+          ln -sf "${_dir}/${!_archive}" .
+          export _humblebundledir="${_dir}"
+      }
+      done
+    done
+    }
+
+    echo "Y to specify path to existing download, blank to specify your humble indie bundle key."
+    echo "Alternatively, place the download into ${_humblebundledir} and retry."
+    read -r _cont
+
+    case "${_cont}" in
+      [yY]) _dlgame
+        ;;
+      *) echo "Specify your humble indie bundle key."
+        echo -n "Humble Indie Bundle key: "
+        read -r _hib
+        [[ -n "${_hib}" ]] && _key="_hib"
+        ;;
+    esac
+  }
+}
+
+_dlgame() {
   _uri="$(curl -s http://www.humblebundle.com/downloads?key="${!_key}" \
     | grep "${!_archive}")"
   echo "  1. Torrent with aria2c"
@@ -59,16 +77,17 @@ done
   read -a _method
   case "${_method}" in
     1)
-      [[ -x "$(type -p aria2c)" ]] && {
-      _uri="${_uri##*data-bt\=\'}"
-      _uri="${_uri%%\'*}" 
-      echo "To resume this download later run:"
-      echo "\`aria2c ${pkgname}.torrent\`"
-      [[ ! -f "${pkgname}.torrent" ]] &&
-        curl -o "${pkgname}.torrent" "${_uri}"
-      aria2c "${pkgname}.torrent" --seed-time=0
-    } || {
-    error "aria2c executable not found! Please install aria2."
+      if [[ -x "$(type -p aria2c)" ]]; then
+        _uri="${_uri##*data-bt\=\'}"
+        _uri="${_uri%%\'*}" 
+        echo "To resume this download later run:"
+        echo "\`aria2c ${pkgname}.torrent\`"
+        [[ ! -f "${pkgname}.torrent" ]] &&
+          curl -o "${pkgname}.torrent" "${_uri}"
+        aria2c "${pkgname}.torrent" --seed-time=0
+      else
+        echo "aria2c executable not found! Please install aria2."
+      fi
     } ;;
   2)
     _uri="${_uri##*data-web\=\'}"
@@ -77,6 +96,6 @@ done
       curl -o "${!_archive}.part" "${_uri}"
     mv "${!_archive}.part" "${!_archive}" ;;
   *) echo "Please choose option 1 or 2." ;;
-      esac
-      source[0]="${!_archive}::${_uri}"
+  esac
 }
+
